"""
mlp_model.py

Purpose
-------
Train and evaluate a Multi-Layer Perceptron (MLP) classifier on the shared
TF-IDF features generated by preprocessing/tfidf_pipeline.py.

Why this file exists
--------------------
An MLP is a neural network made of fully connected layers. In this project,
it serves as the deep learning model paired with the Decision Tree.

Important note
--------------
This baseline uses sklearn's MLPClassifier, which is a good starting point
for quick experimentation. If time permits, this can later be extended to
a PyTorch implementation.

How to run
----------
python -m deep_models.mlp_model

Example with tuning:
python deep_models.mlp_model --hidden-layers 256,128 --max-iter 20 --train-limit 100000
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from scipy.sparse import load_npz
from sklearn.neural_network import MLPClassifier

from evaluation.metrics import evaluate_classification, print_metrics


def parse_hidden_layers(hidden_layers_str: str) -> tuple[int, ...]:
    """
    Convert a comma-separated string like '256,128' into a tuple (256, 128).

    sklearn expects hidden_layer_sizes to be a tuple of integers.
    """
    return tuple(int(x.strip()) for x in hidden_layers_str.split(",") if x.strip())


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments so hidden layer sizes and training settings
    can be changed without editing the source code each time.
    """
    parser = argparse.ArgumentParser(description="Train and evaluate an MLP on TF-IDF features.")

    parser.add_argument(
        "--data-dir",
        type=str,
        default="data/processed/tfidf",
        help="Directory containing X_train.npz, X_test.npz, y_train.npy, and y_test.npy.",
    )
    parser.add_argument(
        "--hidden-layers",
        type=str,
        default="256,128",
        help="Comma-separated hidden layer sizes. Example: 256,128",
    )
    parser.add_argument(
        "--activation",
        type=str,
        default="relu",
        choices=["identity", "logistic", "tanh", "relu"],
        help="Activation function for the hidden layer.",
    )
    parser.add_argument(
        "--learning-rate-init",
        type=float,
        default=0.001,
        help="Initial learning rate.",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.0001,
        help="L2 regularization strength.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=256,
        help="Mini-batch size used by the optimizer.",
    )
    parser.add_argument(
        "--max-iter",
        type=int,
        default=20,
        help="Maximum number of training epochs/iterations.",
    )
    parser.add_argument(
        "--early-stopping",
        action="store_true",
        help="Use early stopping based on validation score.",
    )
    parser.add_argument(
        "--train-limit",
        type=int,
        default=100000,
        help=(
            "Optional cap on training examples used. "
            "This helps speed up experiments while still giving a strong baseline."
        ),
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed for reproducibility.",
    )

    return parser.parse_args()


def load_data(data_dir: str) -> tuple:
    """
    Load the preprocessed TF-IDF matrices and labels from disk.

    These files are created by:
        python preprocessing/tfidf_pipeline.py
    """
    data_path = Path(data_dir)

    X_train = load_npz(data_path / "X_train.npz")
    X_test = load_npz(data_path / "X_test.npz")
    y_train = np.load(data_path / "y_train.npy")
    y_test = np.load(data_path / "y_test.npy")

    return X_train, X_test, y_train, y_test


def maybe_subsample_training_data(X_train, y_train, train_limit: int, random_state: int):
    """
    Optionally use a subset of the training data.

    Why this helps
    --------------
    Training a neural network on the full 560k dataset can take longer,
    especially for debugging and early experimentation.
    """
    if train_limit is None or train_limit >= X_train.shape[0]:
        return X_train, y_train

    rng = np.random.default_rng(random_state)
    indices = rng.choice(X_train.shape[0], size=train_limit, replace=False)

    X_subset = X_train[indices]
    y_subset = y_train[indices]

    return X_subset, y_subset


def main() -> None:
    args = parse_args()

    # ------------------------------------------------------------
    # 1. Load the shared TF-IDF features
    # ------------------------------------------------------------
    X_train, X_test, y_train, y_test = load_data(args.data_dir)

    print(f"Full X_train shape: {X_train.shape}")
    print(f"Full X_test shape : {X_test.shape}")

    # ------------------------------------------------------------
    # 2. Optionally use a smaller training set for faster experiments
    # ------------------------------------------------------------
    X_train_used, y_train_used = maybe_subsample_training_data(
        X_train, y_train, args.train_limit, args.random_state
    )

    print(f"Using training subset shape: {X_train_used.shape}")

    # ------------------------------------------------------------
    # 3. Parse hidden layer sizes from command line
    # ------------------------------------------------------------
    hidden_layer_sizes = parse_hidden_layers(args.hidden_layers)
    print(f"Hidden layer sizes: {hidden_layer_sizes}")

    # ------------------------------------------------------------
    # 4. Build the MLP model
    # ------------------------------------------------------------
    # TODO: Try several hidden layer settings.
    # Suggested values:
    # - 128
    # - 256,128
    # - 512,256
    #
    # TODO: Compare activation="relu" versus activation="tanh".
    #
    # TODO: Try early_stopping on and off, then compare results.
    #
    # TODO: Record how changing max_iter affects performance.

    model = MLPClassifier(
        hidden_layer_sizes=hidden_layer_sizes,
        activation=args.activation,
        solver="adam",
        alpha=args.alpha,
        batch_size=args.batch_size,
        learning_rate_init=args.learning_rate_init,
        max_iter=args.max_iter,
        early_stopping=args.early_stopping,
        random_state=args.random_state,
        verbose=True,  # helpful while training so we can see progress
    )

    # ------------------------------------------------------------
    # 5. Train the model
    # ------------------------------------------------------------
    print("Training MLP...")
    model.fit(X_train_used, y_train_used)

    # ------------------------------------------------------------
    # 6. Predict on the test set
    # ------------------------------------------------------------
    print("Generating predictions...")
    y_pred = model.predict(X_test)

    # ------------------------------------------------------------
    # 7. Evaluate the model
    # ------------------------------------------------------------
    metrics = evaluate_classification(y_test, y_pred)

    print("\nMLP Results")
    print("-" * 40)
    print_metrics(metrics)

    # ------------------------------------------------------------
    # 8. Useful extra information for analysis/writeup
    # ------------------------------------------------------------
    print("\nAdditional Model Info")
    print("-" * 40)
    print(f"Number of training iterations: {model.n_iter_}")
    print(f"Final loss value             : {model.loss_:.6f}")
    print(f"Number of input features     : {X_train.shape[1]}")
    print(f"Number of output classes     : {len(np.unique(y_train))}")

    # If the solver tracked the loss during training, print a few values.
    if hasattr(model, "loss_curve_"):
        print(f"Loss curve length            : {len(model.loss_curve_)}")
        print(f"First loss value             : {model.loss_curve_[0]:.6f}")
        print(f"Last loss value              : {model.loss_curve_[-1]:.6f}")

    # TODO: Add report discussion points such as:
    # - How did the MLP compare against the Decision Tree?
    # - Did deeper hidden layers help?
    # - Did early stopping improve generalization?
    # - Was training time reasonable?


if __name__ == "__main__":
    main()