"""
decision_tree.py

Purpose
-------
Train and evaluate a Decision Tree classifier on the shared TF-IDF features
generated by preprocessing/tfidf_pipeline.py.

Why this file exists
--------------------
Decision Trees cannot work directly on raw text. Instead, we first convert
the text into numerical TF-IDF features, then train the tree on those values.

Important note
--------------
Decision Trees can become very large and very slow on high-dimensional sparse
text data. Because of that, this script supports optional training-set
subsampling so experiments can run in a reasonable amount of time.

How to run
----------
python -m traditional_models.decision_tree

Example with tuning:
python -m traditional_models.decision_tree --max-depth 20 --min-samples-split 10 --train-limit 50000
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from scipy.sparse import load_npz
from sklearn.tree import DecisionTreeClassifier

from evaluation.metrics import evaluate_classification, print_metrics


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments so we can easily test different
    Decision Tree hyperparameters without editing code every time.
    """
    parser = argparse.ArgumentParser(description="Train and evaluate a Decision Tree on TF-IDF features.")

    parser.add_argument(
        "--data-dir",
        type=str,
        default="data/processed/tfidf",
        help="Directory containing X_train.npz, X_test.npz, y_train.npy, and y_test.npy.",
    )
    parser.add_argument(
        "--criterion",
        type=str,
        default="gini",
        choices=["gini", "entropy", "log_loss"],
        help="Function used to measure the quality of a split.",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=20,
        help="Maximum depth of the Decision Tree. Use None for an unconstrained tree.",
    )
    parser.add_argument(
        "--min-samples-split",
        type=int,
        default=10,
        help="Minimum number of samples required to split an internal node.",
    )
    parser.add_argument(
        "--min-samples-leaf",
        type=int,
        default=5,
        help="Minimum number of samples required to be at a leaf node.",
    )
    parser.add_argument(
        "--max-features",
        type=str,
        default=None,
        help="Number of features to consider when looking for the best split. Examples: None, 'sqrt', 'log2'.",
    )
    parser.add_argument(
        "--train-limit",
        type=int,
        default=50000,
        help=(
            "Optional limit on how many training examples to use. "
            "Decision Trees can be slow on the full dataset, so a subset is often practical."
        ),
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed for reproducibility.",
    )

    return parser.parse_args()


def load_data(data_dir: str) -> tuple:
    """
    Load the preprocessed TF-IDF matrices and labels from disk.

    These files are created by:
        python preprocessing/tfidf_pipeline.py

    Returns
    -------
    X_train, X_test, y_train, y_test
    """
    data_path = Path(data_dir)

    # These are sparse matrices saved by scipy.sparse.save_npz
    X_train = load_npz(data_path / "X_train.npz")
    X_test = load_npz(data_path / "X_test.npz")

    # Labels are saved as NumPy arrays
    y_train = np.load(data_path / "y_train.npy")
    y_test = np.load(data_path / "y_test.npy")

    return X_train, X_test, y_train, y_test


def maybe_subsample_training_data(X_train, y_train, train_limit: int, random_state: int):
    """
    Optionally use only part of the training set.

    Why do this?
    ------------
    Decision Trees on large sparse TF-IDF text data can take a very long time
    and may overfit badly. Using a subset can make experiments faster and
    easier to compare.

    If train_limit is None or larger than the dataset size, we keep all data.
    """
    if train_limit is None or train_limit >= X_train.shape[0]:
        return X_train, y_train

    rng = np.random.default_rng(random_state)
    indices = rng.choice(X_train.shape[0], size=train_limit, replace=False)

    X_subset = X_train[indices]
    y_subset = y_train[indices]

    return X_subset, y_subset


def main() -> None:
    args = parse_args()

    # ------------------------------------------------------------
    # 1. Load shared TF-IDF features
    # ------------------------------------------------------------
    X_train, X_test, y_train, y_test = load_data(args.data_dir)

    print(f"Full X_train shape: {X_train.shape}")
    print(f"Full X_test shape : {X_test.shape}")

    # ------------------------------------------------------------
    # 2. Optionally reduce training set size for faster experiments
    # ------------------------------------------------------------
    X_train_used, y_train_used = maybe_subsample_training_data(
        X_train, y_train, args.train_limit, args.random_state
    )

    print(f"Using training subset shape: {X_train_used.shape}")

    # ------------------------------------------------------------
    # 3. Build the Decision Tree model
    # ------------------------------------------------------------
    # TODO: Try several values for max_depth and compare macro F1.
    # Good starting values to test: 10, 20, 30, None
    #
    # TODO: Try criterion="gini" and criterion="entropy" and compare results.
    #
    # TODO: Write down whether the tree appears to overfit
    # (for example: very strong training behavior but weaker test results).

    # Convert the max_features string if needed.
    # argparse gives us strings, but sklearn accepts None, "sqrt", or "log2".
    max_features = args.max_features
    if max_features == "None":
        max_features = None

    model = DecisionTreeClassifier(
        criterion=args.criterion,
        max_depth=args.max_depth,
        min_samples_split=args.min_samples_split,
        min_samples_leaf=args.min_samples_leaf,
        max_features=max_features,
        random_state=args.random_state,
    )

    # ------------------------------------------------------------
    # 4. Train the model
    # ------------------------------------------------------------
    print("Training Decision Tree...")
    model.fit(X_train_used, y_train_used)

    # ------------------------------------------------------------
    # 5. Predict on the test set
    # ------------------------------------------------------------
    print("Generating predictions...")
    y_pred = model.predict(X_test)

    # ------------------------------------------------------------
    # 6. Evaluate using the shared metrics helper
    # ------------------------------------------------------------
    metrics = evaluate_classification(y_test, y_pred)

    print("\nDecision Tree Results")
    print("-" * 40)
    print_metrics(metrics)

    # ------------------------------------------------------------
    # 7. Useful extra info for analysis/writeup
    # ------------------------------------------------------------
    print("\nAdditional Model Info")
    print("-" * 40)
    print(f"Tree depth              : {model.get_depth()}")
    print(f"Number of leaves        : {model.get_n_leaves()}")
    print(f"Number of input features: {X_train.shape[1]}")

    # TODO: Add a short written analysis for the report:
    # - Did the model train quickly or slowly?
    # - Did limiting the training set help?
    # - How did depth affect performance?
    # - Why might Decision Trees struggle on sparse text features?


if __name__ == "__main__":
    main()